[package]
name = "spOS"
version = "0.1.0"
authors = ["Shivam Patel"]
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
spin = "0.9"
volatile = "0.4"

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]